version: '3.2'

services:
  c1:
    container_name: arret04-c1
    image: arret04-client1
    tty: true
    networks:
      - arret04-todo-net
    depends_on:
      - s1
    environment:
      - MONSERVEUR=s1
      - MONNOM=c1

  c2:
    container_name: arret04-c2
    image: arret04-client2
    tty: true
    networks:
      - arret04-todo-net
    depends_on:
      - s1
    environment:
      - MONSERVEUR=s1
      - MONNOM=c2

  c3:
    container_name: arret04-c3
    image: arret04-client3
    tty: true
    networks:
      - arret04-todo-net
    depends_on:
      - s1
    environment:
      - MONSERVEUR=s1
      - MONNOM=c3

  s1:
    container_name: arret04-s1
    image: arret04-serveur
    tty: true
    volumes:
      - "./tmp_todo1:/todo"
    networks:
      - arret04-todo-net

  gestionnaire:
    container_name: arret04-gestionnaire
    image: arret04-gestionnaire
    tty: true
    networks:
      - arret04-todo-net
    environment:
      - MONSERVEUR='s1'
      - MONNOM='c1,c2,c3'
    depends_on:
      - s1

networks:
  arret04-todo-net:
