version: '3.2'

# Définition des services docker
services:
    # Ces services comprennent trois serveurs todo, trois clients, et un superviseur qui observe les tâches
    c1:
      # Premier client - Ajoute et retire des tâches automatiquement
      container_name: arret03-c1
      image: arret03-client1
      tty: true
      networks:
        - arret03-todo-net
      depends_on:
        - s1
      environment:
        - MONSERVEUR=s1
        - MONNOM=c1

    c2:
      container_name: arret03-c2
      image: arret03-client2
      tty: true
      networks:
        - arret03-todo-net
      depends_on:
        - s2
      environment:
        - MONSERVEUR=s2
        - MONNOM=c2

    c3:
      container_name: arret03-c3
      image: arret03-client3
      tty: true
      networks:
        - arret03-todo-net
      depends_on:
        - s3
      environment:
        - MONSERVEUR=s3
        - MONNOM=c3
      
    s1:
      # Premier serveur - Traite les demandes todo
      container_name: arret03-s1
      image: arret03-serveur1
      tty: true
      volumes:
        - "./tmp_todo1:/todo"
      networks:
         - arret03-todo-net

    s2:
      container_name: arret03-s2
      image: arret03-serveur2
      volumes:
        - "./tmp_todo2:/todo"
      tty: true
      networks:
         - arret03-todo-net
      

    s3:
      container_name: arret03-s3
      image: arret03-serveur3
      volumes:
        - "./tmp_todo3:/todo"
      tty: true
      networks:
         - arret03-todo-net

    gestionnaire:
      container_name: arret03-gestionnaire
      image: arret03-gestionnaire
      tty: true
      environment:
        - MONSERVEUR='s1,s2,s3'
        - MONNOM='c1,c2,c3'
      networks:
         - arret03-todo-net

# Réseau par défaut
networks:
  arret03-todo-net:
